[start]
command:/usr/local/etc/rc.d/netglance start
parameters:
type:script
message:starting netglance

[stop]
command:/usr/local/etc/rc.d/netglance stop
parameters:
type:script
message:stopping netglance

[restart]
command:/usr/local/etc/rc.d/netglance restart
parameters:
type:script
message:restarting netglance

[status]
command:/usr/local/etc/rc.d/netglance status; exit 0
parameters:
type:script_output
message:netglance status

[reconfigure]
command:/usr/local/opnsense/scripts/OPNsense/Netglance/setup.sh && /usr/local/etc/rc.d/netglance restart
parameters:
type:script
message:reconfiguring netglance
