PLUGIN_NAME=		netglance
PLUGIN_VERSION=		0.1
PLUGIN_COMMENT=		LAN host discovery and inventory
PLUGIN_DEPENDS=		netglance
PLUGIN_MAINTAINER=	massimo.schiavo.p@gmail.com

.include "../../Mk/plugins.mk"
